server:
  port: 8080

spring:
  application:
    name: mybox
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
      
logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error

jwt-token:
  issue-key: gvklc9fFEKzt6o0t5QJy1GFxUyhe8NsUvCMZzmUiBSTCDIjq6SrDI22YM7iN4kfJ
  valid-time: 600000 # 10분